In [1]:
import numpy as np

In [5]:
# 파이썬 리스트에서 넘파이로 변환
a = [1, 3.14, True, 'hello'] # 리스트
b = np.array(a)

In [7]:
# 리스트 원소 데이터 타입 확인
print(a)
for element in a:
    print('Data Type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data Type of 1 : <class 'int'>
Data Type of 3.14 : <class 'float'>
Data Type of True : <class 'bool'>
Data Type of hello : <class 'str'>


In [8]:
# 넘파이 배열 원소 확인
print(b)
for element in b :
    print('Data Type of {} : {}'.format(element, type(element)))

# 모든 요소가 문자열로 치환됨
# numpy는 하나의 데이터 타입만 받을 수 있기 때문

['1' '3.14' 'True' 'hello']
Data Type of 1 : <class 'numpy.str_'>
Data Type of 3.14 : <class 'numpy.str_'>
Data Type of True : <class 'numpy.str_'>
Data Type of hello : <class 'numpy.str_'>


In [9]:
#  중첩 리스트 생성
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [10]:
# 중첩 리스트 데이터 타입 확인
type(a)

list

In [11]:
# 중첩리스트를 넘파이 배열로 변환 -> 2차원 행렬로 변환
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
# numpy 행렬 테이터 타입 확인
type(b)

numpy.ndarray

In [15]:
# 배열[array]의 shape 확인
# a.shape 은 list기 때문에 안 됨, shape은 numpy가 제공하는 함수이다.
b.shape

(2, 3)

In [16]:
# 배열[array]의 차원 확인
b.ndim

2

In [17]:
# 배열내 총 원소 개수 확인
b.size

6

In [23]:
# 2x3 행렬을 3x2로 바꿔보자
print(b.reshape(3,2))
type(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


numpy.ndarray

In [25]:
# 배열 요소 데이터 타입 변경 : 정수 -> 실수
b = np.array(a, dtype = np.float64) # dtype 인수 설정, list -> numpy and numpy -> numpy
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
# 배열 요소 데이터 타입 변경 : 실수 -> 정수
b = b.astype(np.int64) # 사후 변경시 쉽게 astype 사용 가능, numpy의 메서드이다.
# numpy -> numpy
print(b)

AttributeError: 'list' object has no attribute 'astype'

## 넘파이 배열 인덱싱

In [38]:
# 새로운 배열 arr 생성
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [33]:
# 배열 첫번째 원소 가져오기
arr[0]

1

In [34]:
# 배열 네번째 원소 가져오기
arr[3]

4

In [35]:
# 배열 마지막 원소 가져오기
arr[-1]

5

### 2차원 배열 인덱싱

In [40]:
# 2차원 배열 생성
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
# 1행 1열 원소 가져오기
arr2d[0,0]

1

In [90]:
# 2행 3열 원소 가져오기
arr2d[1,2]

7

In [94]:
arr2d[1]

array([5, 6, 7, 8])

### 배열 슬라이싱

In [47]:
# 슬라이싱 실습에 사용할 넘파이 배열을 arange라는 넘파이 메서드로 만들어보자
arr2 = np.arange(1, 7) # arange(시작 숫자, 끝 숫자) : 시작 숫자부터 끝숫자-1 까지의 번호가 나열되어 저장된다.
arr2 = arr2.reshape(2, 3) # reshape(행, 열) : 원소 개수에 맞춰 reshape을 활용하면 배열의 형태를 바꿀 수 있다.
# 또한 활용에 따라 차원도 변환 가능하다.

print(arr2)

[[1 2 3]
 [4 5 6]]


In [48]:
# 첫번째 행 전체 가져오기
print(arr2[0,:])

[1 2 3]


In [49]:
# 세번째 열 전체 가져오기
print(arr2[:,2])

[3 6]


In [50]:
# 전체 행 두번째 열까지 모두 출력
print(arr2[:,:2])

[[1 2]
 [4 5]]


# 판다스 pandas 소개

### pandas 라이브러리 로딩

In [51]:
import pandas as pd

### 데이터 생성

In [69]:
# 실습에 사용할 샘플 딕셔너리 생성
data = {
    '이름':['아이유', '김연아', '홍길동', '김은숙', '홍의선'],
    '학과':['국문과', '수학과', '전자과', '컴퓨터', '물리'],
    '성적':[3.0, 1.0, 3.5, 2.7, 4.0]
} # dictionary 는 {} 를 이용하여 생성, key : value
# [] 는 list, () 는 tuple, np.array() 는 ndarray
print(data)
print(type(data['이름']))

{'이름': ['아이유', '김연아', '홍길동', '김은숙', '홍의선'], '학과': ['국문과', '수학과', '전자과', '컴퓨터', '물리'], '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}
<class 'list'>


In [70]:
# 딕셔너리 타입인 data를 pd.DataFrame() 인자로 넣어주면 된다.
df = pd.DataFrame(data)
display(df) # 스프레드 시트 형식으로 보여준다.

이름   학과   성적
0  아이유  국문과  3.0
1  김연아  수학과  1.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7
4  홍의선   물리  4.0

### 데이터 csv 로 저장하기

In [71]:
# 데이터 프레임을 csv로 저장 -> to_csv 메소드 이용
df.to_csv('./data/student.csv', sep=',', index=False) # to_csv(저장 경로와 파일 이름 지정, sep = 콤마로 구분, index = False(저장시 인덱스(0,1,2~)가 csv에 포함 안 되도록))

### 데이터 불러오기

In [72]:
# 데이터 로딩은 pandas의 read_csv를 활용하면 됨
df = pd.read_csv('./data/student.csv') # 경로 설정만 해주면 끝
display(df)

이름   학과   성적
0  아이유  국문과  3.0
1  김연아  수학과  1.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7
4  홍의선   물리  4.0

### pandas 원하는 데이터 선택하기

#### 1) 슬라이싱(slicing)

In [74]:
# 데이터 슬라이싱, 1번 행부터 4번 행까지 슬라이싱
df[1:5]

이름   학과   성적
1  김연아  수학과  1.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7
4  홍의선   물리  4.0

In [78]:
# 첫번째 행부터 세번째 행까지 접근
df[0:3]

이름   학과   성적
0  아이유  국문과  3.0
1  김연아  수학과  1.0
2  홍길동  전자과  3.5

In [77]:
# 모든 행 데이터에 접근
df[:]

이름   학과   성적
0  아이유  국문과  3.0
1  김연아  수학과  1.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7
4  홍의선   물리  4.0

#### 2) 인덱싱(indexing)

In [86]:
# df[1] # key error가 뜬다. 데이터 프레임엔 이런 방식으로 인덱싱을 할 수 없기 때문

In [83]:
# 단순 인덱싱 (fancy도 boolean도 아님)
# 컬럼명을 주어 단순 인덱싱을 해보자
df['이름']

0    아이유
1    김연아
2    홍길동
3    김은숙
4    홍의선
Name: 이름, dtype: object

In [82]:
df['성적']

0    3.0
1    1.0
2    3.5
3    2.7
4    4.0
Name: 성적, dtype: float64

#### Fancy Indexing

In [89]:
# 인덱싱 시 리스트로 값을 주면 됨
# '이름'과 '학과'열에만 접근해보자
display(df[['이름','학과']])
type(df[['이름','학과']])

이름   학과
0  아이유  국문과
1  김연아  수학과
2  홍길동  전자과
3  김은숙  컴퓨터
4  홍의선   물리

pandas.core.frame.DataFrame

In [95]:
fancy_list = ['이름', '학과'] # 원하는 컬럼만 리스트로 선택
df[fancy_list] # fancy indexing

이름   학과
0  아이유  국문과
1  김연아  수학과
2  홍길동  전자과
3  김은숙  컴퓨터
4  홍의선   물리

In [96]:
# 컬럼을 입력할 때는 순서는 중요하지 않는다.

#### 슬라이싱 + 인덱싱

In [98]:
df[1:3][['학과', '이름']]

학과   이름
1  수학과  김연아
2  전자과  홍길동

In [99]:
df[['학과', '성적']][0:3]

학과   성적
0  국문과  3.0
1  수학과  1.0
2  전자과  3.5

#### Boolean Indexing

In [100]:
# 연산자 ( ==, !=, > 등)를 이용한 인덱싱 수행

In [102]:
# 수학과 소속인 학생의 데이터만 불러오기
df[df['학과']=='수학과']

이름   학과   성적
1  김연아  수학과  1.0

In [109]:
# 이렇듯 df[ Boolean list ] 로 작동하는 원리이다.
# print(df)
# print(df['성적'] > 2.0) # [True, False, True, True, True]
print(df[df['성적'] > 2.0]) # df[[True, False, True, True, True]]


    이름   학과   성적
0  아이유  국문과  3.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7
4  홍의선   물리  4.0


In [110]:
print(df[df['성적']%1.0 == 0])

    이름   학과   성적
0  아이유  국문과  3.0
1  김연아  수학과  1.0
4  홍의선   물리  4.0


### Pandas 고급 인덱싱 loc & iloc 인덱서

In [113]:
# 기존 방식같이 df[3]으로 행에대한 indexing 불가능하고 df['이름'] 같은 열만 인덱싱 가능
# loc로 행에 대한 indexing 가능
# 한개의 행에 대해서만 loc indexing
display(df.loc[3])
print(type(df.loc[3])) # Series 타입

이름    김은숙
학과    컴퓨터
성적    2.7
Name: 3, dtype: object

<class 'pandas.core.series.Series'>


In [116]:
# 행에 대해서 fancy indexing
df.loc[[0, 2, 4]]

이름   학과   성적
0  아이유  국문과  3.0
2  홍길동  전자과  3.5
4  홍의선   물리  4.0

In [120]:
# 행에 대해서 fancy 인덱싱과 컬럼 슬라이싱
df.loc[[0, 2, 4], : ]

이름   학과   성적
0  아이유  국문과  3.0
2  홍길동  전자과  3.5
4  홍의선   물리  4.0

In [123]:
# 행에 대해서 fancy 인덱싱과 원하는 컬럼 슬라이싱
df.loc[[1,2,3],'이름':'성적'] # 1,2,3 행에서 '이름' 컬럼부터 '성적'까지의 모든 컬럼

이름   학과   성적
1  김연아  수학과  1.0
2  홍길동  전자과  3.5
3  김은숙  컴퓨터  2.7

In [124]:
# 행에 대해서 fancy 인덱싱과 원하는 컬럼 슬라이싱
df.loc[[1,2,3],['이름','성적']] # '이름'과 '성적' 만 fancy indexing

이름   성적
1  김연아  1.0
2  홍길동  3.5
3  김은숙  2.7

In [125]:
# iloc로 컬럼 이름대신 순서를 이용하여 indexing 할 수도 있다
df.iloc[:, 1:] # 이 dataframe에서 0: 이름, 1:학과, 2: 성적 이 된다.

학과   성적
0  국문과  3.0
1  수학과  1.0
2  전자과  3.5
3  컴퓨터  2.7
4   물리  4.0

In [126]:
df.iloc[[0,1,2],[0,2]]

이름   성적
0  아이유  3.0
1  김연아  1.0
2  홍길동  3.5

In [127]:
# loc + boolean indexing + fancy indexing
# 성적이 2로 나누어지지 않는 행에서 이름, 성적만 출력
df.loc[df['성적'] % 2 !=0 , ['이름','성적']]

이름   성적
0  아이유  3.0
1  김연아  1.0
2  홍길동  3.5
3  김은숙  2.7