# Numpy

In [4]:
import numpy as np

In [6]:
# 1차원
a1 = [1,2,3,4,5]

# 배열 변환
a1 = np.array(a1)
print(a1.ndim) # 차원
print(a1.shape) # 1차원은 행, 열 상관없이 하나의 축을 말한다. (5,) 쉼표는 그냥 받아들일 영역, 약속이다.
print(a1.dtype) # 데이터 형식

1
(5,)
int32


In [1]:
# 2 차원
a2 = [[1,3,2,7],[3,2,9,1],[4,6,8,1]]

In [7]:
# 3 차원
a3 = [[[1,3,1],[2,5,2],[3,7,3]],[[1,4,1],[2,6,2],[3,8,3]]]

# 배열 변환
a3 = np.array(a3)
print(a3.ndim)
print(a3.shape)
print(a3.dtype)

3
(2, 3, 3)
int32


# 인덱싱

In [30]:
a2 = np.array(a2)
print(a2)
# 요소 조회
print(a2[1, 2])

print(a2[[1],[2]]) # 행, 열이 둘 다 리스트에 담겨 있음
print(type(a2[[1],[2]])) # 다만 요소가 아닌 배열에 담겨서 출력됨.

print(a2[[1],2]) # 똑같음
print(a2[1,[2]]) # 똑같음
print(a2[[1,2],[1,2]]) # 1차원 (1,1) 과 (2,2) 요소 2개
print(a2[[1,2],1:3]) # 2차원

# 결론은 하나만 리스트(다중 요소)로 들어오면 배열로 결과가 나온다.

[[1 3 2 7]
 [3 2 9 1]
 [4 6 8 1]]
9
[9]
<class 'numpy.ndarray'>
[9]
[9]
[2 8]
[[2 9]
 [6 8]]


In [22]:
# 행 조회
print(a2[1:]) # 1행부터 끝 행까지
print('-'*20)
print(a2[1,:]) # 1행
print('-'*20)

# 열 조회
print(a2[: ,2])
print(a2[:,[1,2]])

[[3 2 9 1]
 [4 6 8 1]]
--------------------
[3 2 9 1]
--------------------
[2 9 8]
[[3 2]
 [2 9]
 [6 8]]
